{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintexpGram where

-- pretty-printer generated by the BNF converter

import AbsexpGram
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)




instance Print Exp where
  prt i e = case e of
   EAnd exp0 exp -> prPrec i 0 (concatD [prt 0 exp0 , doc (showString "and") , prt 1 exp])
   EOr exp0 exp -> prPrec i 0 (concatD [prt 0 exp0 , doc (showString "or") , prt 1 exp])
   ENot exp -> prPrec i 0 (concatD [doc (showString "not") , prt 1 exp])
   EEq exp0 exp -> prPrec i 1 (concatD [prt 1 exp0 , doc (showString "=") , prt 2 exp])
   Elt exp0 exp -> prPrec i 1 (concatD [prt 1 exp0 , doc (showString "<") , prt 2 exp])
   EAdd exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "+") , prt 3 exp])
   ESub exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "-") , prt 3 exp])
   Einc exp -> prPrec i 2 (concatD [doc (showString "Inc(") , prt 0 exp , doc (showString ")")])
   Edec exp -> prPrec i 2 (concatD [doc (showString "Dec(") , prt 0 exp , doc (showString ")")])
   Ediv exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "/") , prt 4 exp])
   EMul exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "*") , prt 4 exp])
   EInt n -> prPrec i 4 (concatD [prt 0 n])
   Evar str -> prPrec i 4 (concatD [prt 0 str])


instance Print Ass where
  prt i e = case e of
   Assign str exp -> prPrec i 0 (concatD [prt 0 str , doc (showString ":=") , prt 0 exp])


instance Print Stm where
  prt i e = case e of
   Sass ass -> prPrec i 0 (concatD [prt 0 ass , doc (showString ";")])
   Sempty  -> prPrec i 0 (concatD [doc (showString ";")])
   Swhile exp stm -> prPrec i 0 (concatD [doc (showString "while") , doc (showString "(") , prt 0 exp , doc (showString ")") , doc (showString "do") , prt 0 stm])
   Selif exp stm0 stm -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , doc (showString "then") , prt 0 stm0 , doc (showString "else") , prt 0 stm , doc (showString "fi")])
   Sif exp stm -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , doc (showString "then") , prt 0 stm , doc (showString "fi")])
   SBlock stm -> prPrec i 0 (concatD [doc (showString "begin") , prt 0 stm , doc (showString "end")])
   Scall str strs -> prPrec i 0 (concatD [doc (showString "call") , prt 0 str , doc (showString "(") , prt 0 strs , doc (showString ")")])
   Sfort ass exp stm -> prPrec i 0 (concatD [doc (showString "for") , prt 0 ass , doc (showString "to") , prt 0 exp , prt 0 stm])
   Sford ass exp stm -> prPrec i 0 (concatD [doc (showString "for") , prt 0 ass , doc (showString "downto") , prt 0 exp , prt 0 stm])
   Sprint str -> prPrec i 0 (concatD [doc (showString "print") , prt 0 str])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print Vdec where
  prt i e = case e of
   VDecl str -> prPrec i 0 (concatD [doc (showString "var") , prt 0 str , doc (showString ";")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Adec where
  prt i e = case e of
   ADecr str -> prPrec i 0 (concatD [doc (showString "var") , prt 0 str])
   ADecv exp -> prPrec i 0 (concatD [prt 0 exp])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ";") , prt 0 xs])

instance Print Pdec where
  prt i e = case e of
   PDecl str adecs stm -> prPrec i 0 (concatD [doc (showString "procedure") , prt 0 str , doc (showString "(") , prt 0 adecs , doc (showString ")") , prt 0 stm , doc (showString ";")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Prg where
  prt i e = case e of
   Prog vdecs pdecs stms -> prPrec i 0 (concatD [prt 0 vdecs , prt 0 pdecs , prt 0 stms])



